### ISSUE TITLE
Not calling trigger() leeds to undefined params

### ISSUE THREAD

**Issue by maxfrigge** [Guria/cerebral-state-router#2]
```
const router = Router(controller, {
  '/:app': {
    ':app': ['router', 'app']
  }
})
```

When I open `http://localhost/foo` the address bar changes to `http://localhost/undefined`.

I am not quite sure what the expected behaviour should be. Should it read my state and set the url accordingly or should the router do nothing at all?

**Comment by Guria** [comment]
@maxfrigge does `['router', 'app']` has initial value?

**Comment by maxfrigge** [comment]
.. Yes it has.. but I had a typo .. it should be `['route', 'app']`.

My bad!
